---
name: Check

'on':
  push:
    branches:
      - main

jobs:
  format:
    name: File formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - run: 'nix fmt . -- --check'
      - run: 'nix run nixpkgs#yamllint -- --strict --format github .'
      - run: 'nix run nixpkgs#deadnix -- .'
      - run: 'nix run nixpkgs#statix -- check'

  check:
    name: Check flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - run: 'nix flake check'
      - run: 'nix build .#default'
